name = "BigBed"
uuid = "97aa930e-cb6b-11e8-0809-05c95cd953e2"
authors = ["Kenta Sato <bicycle1885@gmail.com>", "Daniel C. Jones <dcjones@cs.washington.edu>", "Ben J. Ward <ward9250@gmail.com>", "Ciarán O’Mara <Ciaran.OMara@utas.edu.au>"]
version = "0.1.0"
